# Generated by Django 2.2.4 on 2019-10-08 04:40

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(help_text='\n    Check for icons from : <a href="https://fontawesome.com/icons?d=gallery&m=free" target="_blank">FontAwesome Icons</a>\n    ', max_length=100)),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('description', models.TextField(max_length=5000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, unique=True)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='Enter a number from 0 to 100')),
            ],
            options={
                'ordering': ['-progress'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='testimonial/')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, verbose_name='Description')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='posts/')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, verbose_name='Description')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('mod_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='profile/')),
                ('name', models.CharField(max_length=400, unique=True)),
                ('profile_type', models.CharField(max_length=1500)),
                ('profile_type_list', models.TextField(help_text='Used in top slider', max_length=2000)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.PositiveIntegerField(null=True)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, verbose_name='Bio')),
                ('work_completed', models.PositiveIntegerField(default=0)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('total_clients', models.PositiveIntegerField(default=0)),
                ('awards_won', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('mod_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(to='core.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='posts/')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=5000, verbose_name='Content')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('mod_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Category')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
