# Generated by Django 3.0.2 on 2020-02-16 15:54

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200216_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='large_profile/'),
        ),
    ]
